name: streamlit
channels:
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - altair=4.1.0
  - argh=0.26.2
  - argon2-cffi=21.1.0
  - arrow-cpp=3.0.0
  - astor=0.8.1
  - async_generator=1.10
  - attrs=21.2.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - backports.zoneinfo=0.2.1
  - base58=2.1.0
  - beautifulsoup4=4.10.0
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - boost-cpp=1.69.0
  - boto3=1.18.62
  - botocore=1.21.62
  - branca=0.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bs4=4.10.0
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.10.8
  - cachetools=4.2.4
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=7.1.2
  - cryptography=35.0.0
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - dnspython=1.16.0
  - double-conversion=3.1.5
  - entrypoints=0.3
  - flask=1.1.2
  - folium=0.11.0
  - fpdf=1.7.2
  - freetype=2.10.4
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.24
  - glog=0.5.0
  - grpc-cpp=1.39.0
  - icu=58.2
  - idna=3.1
  - importlib-metadata=4.8.1
  - intel-openmp=2021.3.0
  - ipykernel=6.4.1
  - ipython=7.28.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - itsdangerous=1.1.0
  - jedi=0.18.0
  - jinja2=3.0.2
  - jmespath=0.10.0
  - jpeg=9d
  - jsonschema=4.1.0
  - jupyter_client=7.0.6
  - jupyter_core=4.8.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.2
  - krb5=1.19.2
  - ld_impl_linux-64=2.36.1
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.79.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.14.2
  - libtiff=4.0.10
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbclient=0.5.4
  - nbconvert=6.2.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.4
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1l
  - orc=1.6.9
  - packaging=21.0
  - pandas=1.2.5
  - pandoc=2.14.2
  - pandocfilters=1.5.0
  - parso=0.8.2
  - patsy=0.5.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=6.2.1
  - pip=21.3
  - plotly=5.3.1
  - plotly_express=0.4.1
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - protobuf=3.17.2
  - ptyprocess=0.7.0
  - pyarrow=3.0.0
  - pycparser=2.20
  - pydeck=0.7.0
  - pygments=2.10.0
  - pymongo=3.12.0
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-dotenv=0.19.1
  - python_abi=3.8
  - pytz=2021.3
  - pyyaml=5.4.1
  - pyzmq=22.3.0
  - re2=2021.09.01
  - readline=8.1
  - requests=2.26.0
  - s3transfer=0.5.0
  - scipy=1.7.1
  - send2trash=1.8.0
  - setuptools=58.2.0
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.8
  - soupsieve=2.0.1
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - streamlit=1.0.0
  - streamlit-folium=0.4.0
  - tenacity=8.0.1
  - terminado=0.12.1
  - testpath=0.5.0
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.1.0
  - typing_extensions=3.10.0.2
  - tzdata=2021c
  - tzlocal=3.0
  - uriparser=0.9.3
  - urllib3=1.26.7
  - utf8proc=2.6.1
  - validators=0.18.2
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
